// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simple_erp.Infraestrutura.Persistencia.Contexto;

#nullable disable

namespace simple_erp.Infraestrutura.Migrations
{
    [DbContext(typeof(SimpleErpDbContext))]
    [Migration("20260722051407_Migration01")]
    partial class Migration01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("simple_erp.Core.Modulos.CatalogoDeProdutos.Entidades.Produto", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("Classificacao")
                        .HasColumnType("integer")
                        .HasColumnName("classificacao");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("UnidadeDeMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade_de_medida");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_codigo");

                    b.ToTable("produtos", "catalogo");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Estoque.Entidades.MovimentacaoDeEstoque", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<DateTime>("DataMovimentacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao_utc");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("origem");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("SaldoResultante")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("saldo_resultante");

                    b.Property<int>("Sentido")
                        .HasColumnType("integer")
                        .HasColumnName("sentido");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes");

                    b.HasIndex("IdProduto", "DataMovimentacaoUtc")
                        .HasDatabaseName("ix_movimentacoes_produto_data");

                    b.ToTable("movimentacoes", "estoque");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Estoque.Entidades.SaldoDeEstoque", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade_atual");

                    b.HasKey("Id")
                        .HasName("pk_saldos");

                    b.HasIndex("IdProduto")
                        .IsUnique()
                        .HasDatabaseName("ux_saldos_id_produto");

                    b.ToTable("saldos", "estoque");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Financeiro.Entidades.Titulo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<DateTime>("DataVencimentoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento_utc");

                    b.Property<long>("IdParceiro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_parceiro");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("origem");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_original");

                    b.Property<string>("_baixas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("baixas");

                    b.HasKey("Id")
                        .HasName("pk_titulos");

                    b.HasIndex("IdParceiro", "DataVencimentoUtc")
                        .HasDatabaseName("ix_titulos_parceiro_vencimento");

                    b.ToTable("titulos", "financeiro");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.ParceirosComerciais.Entidades.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_documento");

                    b.ToTable("clientes", "parceiros");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.ParceirosComerciais.Entidades.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ux_fornecedores_documento");

                    b.ToTable("fornecedores", "parceiros");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Producao.Composicao.Entidades.ComposicaoDeProduto", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<long>("IdProdutoFabricado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto_fabricado");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.Property<string>("_itens")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("itens");

                    b.HasKey("Id")
                        .HasName("pk_composicoes_de_produto");

                    b.HasIndex("IdProdutoFabricado", "Versao")
                        .IsUnique()
                        .HasDatabaseName("ux_composicoes_produto_versao");

                    b.ToTable("composicoes_de_produto", "producao");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Producao.Entidades.OrdemDeProducao", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<long>("IdComposicao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_composicao");

                    b.Property<long>("IdProdutoFabricado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto_fabricado");

                    b.Property<decimal>("QuantidadeAProduzir")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade_a_produzir");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("_necessidades")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("necessidades");

                    b.HasKey("Id")
                        .HasName("pk_ordens_de_producao");

                    b.HasIndex("IdProdutoFabricado", "DataCriacaoUtc")
                        .HasDatabaseName("ix_ordens_de_producao_produto_data");

                    b.ToTable("ordens_de_producao", "producao");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Suprimentos.Entidades.PedidoDeCompra", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<long>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("_itens")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("itens");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_de_compra");

                    b.HasIndex("IdFornecedor", "DataCriacaoUtc")
                        .HasDatabaseName("ix_pedidos_de_compra_fornecedor_data");

                    b.ToTable("pedidos_de_compra", "suprimentos");
                });

            modelBuilder.Entity("simple_erp.Core.Modulos.Vendas.Entidades.PedidoDeVenda", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_utc");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao_utc");

                    b.Property<decimal>("DescontoDoPedido")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("desconto_do_pedido");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("_itens")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("itens");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_de_venda");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_pedidos_de_venda_numero");

                    b.HasIndex("IdCliente", "DataCriacaoUtc")
                        .HasDatabaseName("ix_pedidos_de_venda_cliente_data");

                    b.ToTable("pedidos_de_venda", "vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
